import Head from 'next/head'
import MainPageSlider from "@/components/public/MainPageSlider";
import InfoSection from "@/components/public/InfoSection";
import WeCare from "@/components/public/WeCare";
import Certifications from "@/components/public/Certifications";
import Features from "@/components/public/Features";
// import Parts from "@/components/public/Parts";
import Smile from "@/components/public/smile/smile";
import Department from "@/components/public/Department";
import OurDentists from "@/components/public/OurDentists";
import Contact from "@/components/public/contact/Contact";
import Blogs from "@/components/public/Blogs";



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <MainPageSlider data={[]}></MainPageSlider>
          <InfoSection></InfoSection>
          <WeCare></WeCare>
          <Features></Features>
          <Certifications data={[]}></Certifications>
          <Smile></Smile>
          <Department></Department>
          <OurDentists></OurDentists>
          {/*<Contact></Contact>*/}
          <Blogs></Blogs>
      </main>
    </>
  )
}
